//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.app.drug.requests;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppliedDocumentType", namespace = "http://lanit.ru/ws/commons", propOrder = {
    "codeDocument",
    "name",
    "number",
    "url",
    "type",
    "digestValue"
})
public class AppliedDocumentType {

    @XmlElement(name = "CodeDocument", namespace = "http://lanit.ru/ws/commons")
    protected String codeDocument;
    @XmlElement(name = "Name", namespace = "http://lanit.ru/ws/commons", required = true)
    protected String name;
    @XmlElement(name = "Number", namespace = "http://lanit.ru/ws/commons")
    protected String number;
    @XmlElement(name = "URL", namespace = "http://lanit.ru/ws/commons", required = true)
    protected String url;
    @XmlElement(name = "Type", namespace = "http://lanit.ru/ws/commons", required = true)
    protected String type;
    @XmlElement(name = "DigestValue", namespace = "http://lanit.ru/ws/commons")
    protected byte[] digestValue;
    @XmlAttribute(name = "ID", namespace = "http://lanit.ru/ws/commons")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    public String getCodeDocument() {
        return codeDocument;
    }

    public void setCodeDocument(String value) {
        this.codeDocument = value;
    }


    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String value) {
        this.number = value;
    }

    public String getURL() {
        return url;
    }

    public void setURL(String value) {
        this.url = value;
    }

    public String getType() {
        return type;
    }

    public void setType(String value) {
        this.type = value;
    }

    public byte[] getDigestValue() {
        return digestValue;
    }

    public void setDigestValue(byte[] value) {
        this.digestValue = ((byte[]) value);
    }

    public String getID() {
        return id;
    }

    public void setID(String value) {
        this.id = value;
    }

}
