//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.lanit.ws.pgu.reform_client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReformClientRequest_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "ReformClientRequest");
    private final static QName _AddressTypeDescription_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Description");
    private final static QName _AddressTypeStreet_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Street");
    private final static QName _AddressTypeConstruction_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Construction");
    private final static QName _AddressTypeDistrict_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "District");
    private final static QName _AddressTypeFlat_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Flat");
    private final static QName _AddressTypeBuilding_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Building");
    private final static QName _AddressTypeHouse_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "House");
    private final static QName _AddressTypePostIndex_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "PostIndex");
    private final static QName _DictTypeName_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Name");
    private final static QName _LicensiatIPTypeCountryCode_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "CountryCode");
    private final static QName _LicensiatIPTypeSecondName_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "SecondName");
    private final static QName _LicensiatULTypeShortName_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "ShortName");
    private final static QName _LicensiatULTypeFirmName_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "FirmName");
    private final static QName _RepresentativeInfoTypeRepresentativeSecondName_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "RepresentativeSecondName");
    private final static QName _RegistrationInfoTypeInnDate_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "InnDate");
    private final static QName _RegistrationInfoTypePhone_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Phone");
    private final static QName _RegistrationInfoTypeInnWho_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "InnWho");
    private final static QName _RegistrationInfoTypeFax_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Fax");
    private final static QName _RegistrationInfoTypeRegDepartAddress_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "RegDepartAddress");
    private final static QName _RegistrationInfoTypeRegNoNumber_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "RegNoNumber");
    private final static QName _RegistrationInfoTypeInnSeries_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "InnSeries");
    private final static QName _RegistrationInfoTypeRepresentativeInfo_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "RepresentativeInfo");
    private final static QName _RegistrationInfoTypeRegNoName_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "RegNoName");
    private final static QName _RegistrationInfoTypeInnForm_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "InnForm");
    private final static QName _RegistrationInfoTypeInnName_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "InnName");
    private final static QName _RegistrationInfoTypeEmail_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "Email");
    private final static QName _RegistrationInfoTypeRegNoSeries_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "RegNoSeries");
    private final static QName _RegistrationInfoTypeInnNumber_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "InnNumber");
    private final static QName _RegistrationInfoTypeRegNoForm_QNAME = new QName("http://lanit.ru/ws/pgu/reform_client", "RegNoForm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.lanit.ws.pgu.reform_client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link DictType }
     * 
     */
    public DictType createDictType() {
        return new DictType();
    }

    /**
     * Create an instance of {@link LicensiatULType }
     * 
     */
    public LicensiatULType createLicensiatULType() {
        return new LicensiatULType();
    }

    /**
     * Create an instance of {@link LicensiatIPType }
     * 
     */
    public LicensiatIPType createLicensiatIPType() {
        return new LicensiatIPType();
    }

    /**
     * Create an instance of {@link RequestIPType }
     * 
     */
    public RequestIPType createRequestIPType() {
        return new RequestIPType();
    }

    /**
     * Create an instance of {@link ReformClientRequestType }
     * 
     */
    public ReformClientRequestType createReformClientRequestType() {
        return new ReformClientRequestType();
    }

    /**
     * Create an instance of {@link RequestBaseType }
     * 
     */
    public RequestBaseType createRequestBaseType() {
        return new RequestBaseType();
    }

    /**
     * Create an instance of {@link RepresentativeInfoType }
     * 
     */
    public RepresentativeInfoType createRepresentativeInfoType() {
        return new RepresentativeInfoType();
    }

    /**
     * Create an instance of {@link RequestULType }
     * 
     */
    public RequestULType createRequestULType() {
        return new RequestULType();
    }

    /**
     * Create an instance of {@link RegistrationInfoType }
     * 
     */
    public RegistrationInfoType createRegistrationInfoType() {
        return new RegistrationInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReformClientRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "ReformClientRequest")
    public JAXBElement<ReformClientRequestType> createReformClientRequest(ReformClientRequestType value) {
        return new JAXBElement<ReformClientRequestType>(_ReformClientRequest_QNAME, ReformClientRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Description", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeDescription(String value) {
        return new JAXBElement<String>(_AddressTypeDescription_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Street", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeStreet(String value) {
        return new JAXBElement<String>(_AddressTypeStreet_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Construction", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeConstruction(String value) {
        return new JAXBElement<String>(_AddressTypeConstruction_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "District", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeDistrict(String value) {
        return new JAXBElement<String>(_AddressTypeDistrict_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Flat", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeFlat(String value) {
        return new JAXBElement<String>(_AddressTypeFlat_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Building", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeBuilding(String value) {
        return new JAXBElement<String>(_AddressTypeBuilding_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "House", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeHouse(String value) {
        return new JAXBElement<String>(_AddressTypeHouse_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "PostIndex", scope = AddressType.class)
    public JAXBElement<String> createAddressTypePostIndex(String value) {
        return new JAXBElement<String>(_AddressTypePostIndex_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Name", scope = DictType.class)
    public JAXBElement<String> createDictTypeName(String value) {
        return new JAXBElement<String>(_DictTypeName_QNAME, String.class, DictType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DictType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "CountryCode", scope = LicensiatIPType.class)
    public JAXBElement<DictType> createLicensiatIPTypeCountryCode(DictType value) {
        return new JAXBElement<DictType>(_LicensiatIPTypeCountryCode_QNAME, DictType.class, LicensiatIPType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "SecondName", scope = LicensiatIPType.class)
    public JAXBElement<String> createLicensiatIPTypeSecondName(String value) {
        return new JAXBElement<String>(_LicensiatIPTypeSecondName_QNAME, String.class, LicensiatIPType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "ShortName", scope = LicensiatULType.class)
    public JAXBElement<String> createLicensiatULTypeShortName(String value) {
        return new JAXBElement<String>(_LicensiatULTypeShortName_QNAME, String.class, LicensiatULType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "FirmName", scope = LicensiatULType.class)
    public JAXBElement<String> createLicensiatULTypeFirmName(String value) {
        return new JAXBElement<String>(_LicensiatULTypeFirmName_QNAME, String.class, LicensiatULType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "RepresentativeSecondName", scope = RepresentativeInfoType.class)
    public JAXBElement<String> createRepresentativeInfoTypeRepresentativeSecondName(String value) {
        return new JAXBElement<String>(_RepresentativeInfoTypeRepresentativeSecondName_QNAME, String.class, RepresentativeInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "InnDate", scope = RegistrationInfoType.class)
    public JAXBElement<XMLGregorianCalendar> createRegistrationInfoTypeInnDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RegistrationInfoTypeInnDate_QNAME, XMLGregorianCalendar.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Phone", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypePhone(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypePhone_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "InnWho", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeInnWho(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeInnWho_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Fax", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeFax(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeFax_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "RegDepartAddress", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeRegDepartAddress(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeRegDepartAddress_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "RegNoNumber", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeRegNoNumber(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeRegNoNumber_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "InnSeries", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeInnSeries(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeInnSeries_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepresentativeInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "RepresentativeInfo", scope = RegistrationInfoType.class)
    public JAXBElement<RepresentativeInfoType> createRegistrationInfoTypeRepresentativeInfo(RepresentativeInfoType value) {
        return new JAXBElement<RepresentativeInfoType>(_RegistrationInfoTypeRepresentativeInfo_QNAME, RepresentativeInfoType.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "RegNoName", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeRegNoName(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeRegNoName_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "InnForm", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeInnForm(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeInnForm_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "InnName", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeInnName(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeInnName_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "Email", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeEmail(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeEmail_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "RegNoSeries", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeRegNoSeries(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeRegNoSeries_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "InnNumber", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeInnNumber(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeInnNumber_QNAME, String.class, RegistrationInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/reform_client", name = "RegNoForm", scope = RegistrationInfoType.class)
    public JAXBElement<String> createRegistrationInfoTypeRegNoForm(String value) {
        return new JAXBElement<String>(_RegistrationInfoTypeRegNoForm_QNAME, String.class, RegistrationInfoType.class, value);
    }

}
