//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Общие данные
 * 
 * <p>Java class for RequestBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Authority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActivityKind" type="{http://lanit.ru/ws/pgu/reform_client}DictType"/>
 *         &lt;element name="ProcessType" type="{http://lanit.ru/ws/pgu/reform_client}DictType"/>
 *         &lt;element name="Reason" type="{http://lanit.ru/ws/pgu/reform_client}DictType" maxOccurs="unbounded"/>
 *         &lt;element name="RegAddress" type="{http://lanit.ru/ws/pgu/reform_client}AddressType"/>
 *         &lt;element name="RegistrationInfo" type="{http://lanit.ru/ws/pgu/reform_client}RegistrationInfoType"/>
 *         &lt;element name="DeliveryPlaceKind" type="{http://lanit.ru/ws/pgu/reform_client}DeliveryPlaceType"/>
 *         &lt;element name="DeliveryPlace" type="{http://lanit.ru/ws/pgu/reform_client}DictType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestBaseType", namespace = "http://lanit.ru/ws/pgu/reform_client", propOrder = {
    "authority",
    "activityKind",
    "processType",
    "reason",
    "regAddress",
    "registrationInfo",
    "deliveryPlaceKind",
    "deliveryPlace"
})
@XmlSeeAlso({
    RequestIPType.class,
    RequestULType.class
})
public class RequestBaseType {

    @XmlElement(name = "Authority", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected String authority;
    @XmlElement(name = "ActivityKind", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected DictType activityKind;
    @XmlElement(name = "ProcessType", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected DictType processType;
    @XmlElement(name = "Reason", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected List<DictType> reason;
    @XmlElement(name = "RegAddress", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected AddressType regAddress;
    @XmlElement(name = "RegistrationInfo", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected RegistrationInfoType registrationInfo;
    @XmlElement(name = "DeliveryPlaceKind", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected String deliveryPlaceKind;
    @XmlElement(name = "DeliveryPlace", namespace = "http://lanit.ru/ws/pgu/reform_client", required = true)
    protected DictType deliveryPlace;

    /**
     * Gets the value of the authority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * Sets the value of the authority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthority(String value) {
        this.authority = value;
    }

    /**
     * Gets the value of the activityKind property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getActivityKind() {
        return activityKind;
    }

    /**
     * Sets the value of the activityKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setActivityKind(DictType value) {
        this.activityKind = value;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setProcessType(DictType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DictType }
     * 
     * 
     */
    public List<DictType> getReason() {
        if (reason == null) {
            reason = new ArrayList<DictType>();
        }
        return this.reason;
    }

    /**
     * Gets the value of the regAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getRegAddress() {
        return regAddress;
    }

    /**
     * Sets the value of the regAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setRegAddress(AddressType value) {
        this.regAddress = value;
    }

    /**
     * Gets the value of the registrationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationInfoType }
     *     
     */
    public RegistrationInfoType getRegistrationInfo() {
        return registrationInfo;
    }

    /**
     * Sets the value of the registrationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationInfoType }
     *     
     */
    public void setRegistrationInfo(RegistrationInfoType value) {
        this.registrationInfo = value;
    }

    /**
     * Gets the value of the deliveryPlaceKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlaceKind() {
        return deliveryPlaceKind;
    }

    /**
     * Sets the value of the deliveryPlaceKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlaceKind(String value) {
        this.deliveryPlaceKind = value;
    }

    /**
     * Gets the value of the deliveryPlace property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getDeliveryPlace() {
        return deliveryPlace;
    }

    /**
     * Sets the value of the deliveryPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setDeliveryPlace(DictType value) {
        this.deliveryPlace = value;
    }

}
