//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.gosuslugi.smev.request.req.rev120528;

import ru.lanit.ws.pgu.beans.application.gosuslugi.smev.request.rev111111.AppliedDocumentsType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestData" type="{http://smev.gosuslugi.ru/request/req/rev120528}RequestDataType"/>
 *         &lt;element ref="{http://smev.gosuslugi.ru/request/rev111111}AppliedDocuments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestData",
    "appliedDocuments"
})
@XmlRootElement(name = "Data", namespace = "http://smev.gosuslugi.ru/request/req/rev120528")
public class Data {

    @XmlElement(name = "RequestData", namespace = "http://smev.gosuslugi.ru/request/req/rev120528", required = true)
    protected RequestDataType requestData;
    @XmlElement(name = "AppliedDocuments", namespace = "http://smev.gosuslugi.ru/request/rev111111")
    protected AppliedDocumentsType appliedDocuments;

    /**
     * Gets the value of the requestData property.
     * 
     * @return
     *     possible object is
     *     {@link RequestDataType }
     *     
     */
    public RequestDataType getRequestData() {
        return requestData;
    }

    /**
     * Sets the value of the requestData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestDataType }
     *     
     */
    public void setRequestData(RequestDataType value) {
        this.requestData = value;
    }

    /**
     * Gets the value of the appliedDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link AppliedDocumentsType }
     *     
     */
    public AppliedDocumentsType getAppliedDocuments() {
        return appliedDocuments;
    }

    /**
     * Sets the value of the appliedDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliedDocumentsType }
     *     
     */
    public void setAppliedDocuments(AppliedDocumentsType value) {
        this.appliedDocuments = value;
    }

}
