//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.gosuslugi.smev.request.req.rev120528;

import ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.duplic_license.DuplicLicenseRequestType;
import ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.get_license.GetLicenseRequestType;
import ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_client.ReformClientRequestType;
import ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_license.ReformLicenseRequestType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Используется для передачи данных заявки. Данные заявки могут быть переданы только внутри
 *                 RequestData
 *             
 * 
 * <p>Java class for RequestDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://lanit.ru/ws/pgu/get_license}GetLicenseRequest"/>
 *           &lt;element ref="{http://lanit.ru/ws/pgu/reform_client}ReformClientRequest"/>
 *           &lt;element ref="{http://lanit.ru/ws/pgu/reform_license}ReformLicenseRequest"/>
 *           &lt;element ref="{http://lanit.ru/ws/pgu/duplic_license}DuplicLicenseRequest"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestDataType", namespace = "http://smev.gosuslugi.ru/request/req/rev120528", propOrder = {
    "getLicenseRequest",
    "reformClientRequest",
    "reformLicenseRequest",
    "duplicLicenseRequest"
})
public class RequestDataType {

    @XmlElement(name = "GetLicenseRequest", namespace = "http://lanit.ru/ws/pgu/get_license")
    protected GetLicenseRequestType getLicenseRequest;
    @XmlElement(name = "ReformClientRequest", namespace = "http://lanit.ru/ws/pgu/reform_client")
    protected ReformClientRequestType reformClientRequest;
    @XmlElement(name = "ReformLicenseRequest", namespace = "http://lanit.ru/ws/pgu/reform_license")
    protected ReformLicenseRequestType reformLicenseRequest;
    @XmlElement(name = "DuplicLicenseRequest", namespace = "http://lanit.ru/ws/pgu/duplic_license")
    protected DuplicLicenseRequestType duplicLicenseRequest;

    /**
     * Gets the value of the getLicenseRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetLicenseRequestType }
     *     
     */
    public GetLicenseRequestType getGetLicenseRequest() {
        return getLicenseRequest;
    }

    /**
     * Sets the value of the getLicenseRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetLicenseRequestType }
     *     
     */
    public void setGetLicenseRequest(GetLicenseRequestType value) {
        this.getLicenseRequest = value;
    }

    /**
     * Gets the value of the reformClientRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReformClientRequestType }
     *     
     */
    public ReformClientRequestType getReformClientRequest() {
        return reformClientRequest;
    }

    /**
     * Sets the value of the reformClientRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReformClientRequestType }
     *     
     */
    public void setReformClientRequest(ReformClientRequestType value) {
        this.reformClientRequest = value;
    }

    /**
     * Gets the value of the reformLicenseRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReformLicenseRequestType }
     *     
     */
    public ReformLicenseRequestType getReformLicenseRequest() {
        return reformLicenseRequest;
    }

    /**
     * Sets the value of the reformLicenseRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReformLicenseRequestType }
     *     
     */
    public void setReformLicenseRequest(ReformLicenseRequestType value) {
        this.reformLicenseRequest = value;
    }

    /**
     * Gets the value of the duplicLicenseRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DuplicLicenseRequestType }
     *     
     */
    public DuplicLicenseRequestType getDuplicLicenseRequest() {
        return duplicLicenseRequest;
    }

    /**
     * Sets the value of the duplicLicenseRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DuplicLicenseRequestType }
     *     
     */
    public void setDuplicLicenseRequest(DuplicLicenseRequestType value) {
        this.duplicLicenseRequest = value;
    }

}
