//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.duplic_license;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LicensiatIPType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LicensiatIPType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecondName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PassportType" type="{http://lanit.ru/ws/pgu/duplic_license}DictType"/>
 *         &lt;element name="PassportSeries" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PassportNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PassportWho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PassportDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CountryCode" type="{http://lanit.ru/ws/pgu/duplic_license}DictType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LicensiatIPType", namespace = "http://lanit.ru/ws/pgu/duplic_license", propOrder = {
    "lastName",
    "firstName",
    "secondName",
    "passportType",
    "passportSeries",
    "passportNo",
    "passportWho",
    "passportDate",
    "countryCode"
})
public class LicensiatIPType {

    @XmlElement(name = "LastName", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String lastName;
    @XmlElement(name = "FirstName", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String firstName;
    @XmlElementRef(name = "SecondName", namespace = "http://lanit.ru/ws/pgu/duplic_license", type = JAXBElement.class)
    protected JAXBElement<String> secondName;
    @XmlElement(name = "PassportType", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected DictType passportType;
    @XmlElement(name = "PassportSeries", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String passportSeries;
    @XmlElement(name = "PassportNo", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String passportNo;
    @XmlElement(name = "PassportWho", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String passportWho;
    @XmlElement(name = "PassportDate", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar passportDate;
    @XmlElementRef(name = "CountryCode", namespace = "http://lanit.ru/ws/pgu/duplic_license", type = JAXBElement.class)
    protected JAXBElement<DictType> countryCode;

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the secondName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSecondName() {
        return secondName;
    }

    /**
     * Sets the value of the secondName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSecondName(JAXBElement<String> value) {
        this.secondName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the passportType property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getPassportType() {
        return passportType;
    }

    /**
     * Sets the value of the passportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setPassportType(DictType value) {
        this.passportType = value;
    }

    /**
     * Gets the value of the passportSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportSeries() {
        return passportSeries;
    }

    /**
     * Sets the value of the passportSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportSeries(String value) {
        this.passportSeries = value;
    }

    /**
     * Gets the value of the passportNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportNo() {
        return passportNo;
    }

    /**
     * Sets the value of the passportNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportNo(String value) {
        this.passportNo = value;
    }

    /**
     * Gets the value of the passportWho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportWho() {
        return passportWho;
    }

    /**
     * Sets the value of the passportWho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportWho(String value) {
        this.passportWho = value;
    }

    /**
     * Gets the value of the passportDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPassportDate() {
        return passportDate;
    }

    /**
     * Sets the value of the passportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPassportDate(XMLGregorianCalendar value) {
        this.passportDate = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DictType }{@code >}
     *     
     */
    public JAXBElement<DictType> getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DictType }{@code >}
     *     
     */
    public void setCountryCode(JAXBElement<DictType> value) {
        this.countryCode = ((JAXBElement<DictType> ) value);
    }

}
