//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.duplic_license;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Общие данные
 * 
 * <p>Java class for RequestBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Authority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActivityKind" type="{http://lanit.ru/ws/pgu/duplic_license}DictType"/>
 *         &lt;element name="ProcessType" type="{http://lanit.ru/ws/pgu/duplic_license}DictType"/>
 *         &lt;element name="LicenseNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BlankSeries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BlankNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegAddress" type="{http://lanit.ru/ws/pgu/duplic_license}AddressType"/>
 *         &lt;element name="RegistrationInfo" type="{http://lanit.ru/ws/pgu/duplic_license}RegistrationInfoType"/>
 *         &lt;element name="DeliveryPlaceKind" type="{http://lanit.ru/ws/pgu/duplic_license}DeliveryPlaceType"/>
 *         &lt;element name="DeliveryPlace" type="{http://lanit.ru/ws/pgu/duplic_license}DictType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestBaseType", namespace = "http://lanit.ru/ws/pgu/duplic_license", propOrder = {
    "authority",
    "activityKind",
    "processType",
    "licenseNo",
    "blankSeries",
    "blankNo",
    "regAddress",
    "registrationInfo",
    "deliveryPlaceKind",
    "deliveryPlace"
})
@XmlSeeAlso({
    RequestIPType.class,
    RequestULType.class
})
public class RequestBaseType {

    @XmlElement(name = "Authority", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String authority;
    @XmlElement(name = "ActivityKind", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected DictType activityKind;
    @XmlElement(name = "ProcessType", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected DictType processType;
    @XmlElement(name = "LicenseNo", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String licenseNo;
    @XmlElementRef(name = "BlankSeries", namespace = "http://lanit.ru/ws/pgu/duplic_license", type = JAXBElement.class)
    protected JAXBElement<String> blankSeries;
    @XmlElementRef(name = "BlankNo", namespace = "http://lanit.ru/ws/pgu/duplic_license", type = JAXBElement.class)
    protected JAXBElement<String> blankNo;
    @XmlElement(name = "RegAddress", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected AddressType regAddress;
    @XmlElement(name = "RegistrationInfo", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected RegistrationInfoType registrationInfo;
    @XmlElement(name = "DeliveryPlaceKind", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected String deliveryPlaceKind;
    @XmlElement(name = "DeliveryPlace", namespace = "http://lanit.ru/ws/pgu/duplic_license", required = true)
    protected DictType deliveryPlace;

    /**
     * Gets the value of the authority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * Sets the value of the authority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthority(String value) {
        this.authority = value;
    }

    /**
     * Gets the value of the activityKind property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getActivityKind() {
        return activityKind;
    }

    /**
     * Sets the value of the activityKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setActivityKind(DictType value) {
        this.activityKind = value;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setProcessType(DictType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the licenseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * Sets the value of the licenseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNo(String value) {
        this.licenseNo = value;
    }

    /**
     * Gets the value of the blankSeries property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBlankSeries() {
        return blankSeries;
    }

    /**
     * Sets the value of the blankSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBlankSeries(JAXBElement<String> value) {
        this.blankSeries = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the blankNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBlankNo() {
        return blankNo;
    }

    /**
     * Sets the value of the blankNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBlankNo(JAXBElement<String> value) {
        this.blankNo = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the regAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getRegAddress() {
        return regAddress;
    }

    /**
     * Sets the value of the regAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setRegAddress(AddressType value) {
        this.regAddress = value;
    }

    /**
     * Gets the value of the registrationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationInfoType }
     *     
     */
    public RegistrationInfoType getRegistrationInfo() {
        return registrationInfo;
    }

    /**
     * Sets the value of the registrationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationInfoType }
     *     
     */
    public void setRegistrationInfo(RegistrationInfoType value) {
        this.registrationInfo = value;
    }

    /**
     * Gets the value of the deliveryPlaceKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlaceKind() {
        return deliveryPlaceKind;
    }

    /**
     * Sets the value of the deliveryPlaceKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlaceKind(String value) {
        this.deliveryPlaceKind = value;
    }

    /**
     * Gets the value of the deliveryPlace property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getDeliveryPlace() {
        return deliveryPlace;
    }

    /**
     * Sets the value of the deliveryPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setDeliveryPlace(DictType value) {
        this.deliveryPlace = value;
    }

}
