//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_license;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Данные о документе, устанавливающем право владения ТС
 * 
 * <p>Java class for CarDocInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarDocInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CarDocType" type="{http://lanit.ru/ws/pgu/reform_license}DictType"/>
 *         &lt;element name="CarDocSeries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CarDocNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CarDocDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CarDocDateExp" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarDocInfoType", namespace = "http://lanit.ru/ws/pgu/reform_license", propOrder = {
    "carDocType",
    "carDocSeries",
    "carDocNumber",
    "carDocDate",
    "carDocDateExp"
})
public class CarDocInfoType {

    @XmlElement(name = "CarDocType", namespace = "http://lanit.ru/ws/pgu/reform_license", required = true)
    protected DictType carDocType;
    @XmlElementRef(name = "CarDocSeries", namespace = "http://lanit.ru/ws/pgu/reform_license", type = JAXBElement.class)
    protected JAXBElement<String> carDocSeries;
    @XmlElement(name = "CarDocNumber", namespace = "http://lanit.ru/ws/pgu/reform_license", required = true)
    protected String carDocNumber;
    @XmlElement(name = "CarDocDate", namespace = "http://lanit.ru/ws/pgu/reform_license", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar carDocDate;
    @XmlElementRef(name = "CarDocDateExp", namespace = "http://lanit.ru/ws/pgu/reform_license", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> carDocDateExp;

    /**
     * Gets the value of the carDocType property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getCarDocType() {
        return carDocType;
    }

    /**
     * Sets the value of the carDocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setCarDocType(DictType value) {
        this.carDocType = value;
    }

    /**
     * Gets the value of the carDocSeries property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCarDocSeries() {
        return carDocSeries;
    }

    /**
     * Sets the value of the carDocSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCarDocSeries(JAXBElement<String> value) {
        this.carDocSeries = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the carDocNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarDocNumber() {
        return carDocNumber;
    }

    /**
     * Sets the value of the carDocNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarDocNumber(String value) {
        this.carDocNumber = value;
    }

    /**
     * Gets the value of the carDocDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCarDocDate() {
        return carDocDate;
    }

    /**
     * Sets the value of the carDocDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCarDocDate(XMLGregorianCalendar value) {
        this.carDocDate = value;
    }

    /**
     * Gets the value of the carDocDateExp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getCarDocDateExp() {
        return carDocDateExp;
    }

    /**
     * Sets the value of the carDocDateExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setCarDocDateExp(JAXBElement<XMLGregorianCalendar> value) {
        this.carDocDateExp = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

}
