//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_license;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Список атрибутов автомобилей
 * 
 * <p>Java class for CarsInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarsInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CarInfo" type="{http://lanit.ru/ws/pgu/reform_license}CarInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarsInfoType", namespace = "http://lanit.ru/ws/pgu/reform_license", propOrder = {
    "carInfo"
})
public class CarsInfoType {

    @XmlElement(name = "CarInfo", namespace = "http://lanit.ru/ws/pgu/reform_license", required = true)
    protected CarInfoType carInfo;

    /**
     * Gets the value of the carInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CarInfoType }
     *     
     */
    public CarInfoType getCarInfo() {
        return carInfo;
    }

    /**
     * Sets the value of the carInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarInfoType }
     *     
     */
    public void setCarInfo(CarInfoType value) {
        this.carInfo = value;
    }

}
