//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_license;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReformLicenseRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReformLicenseRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientType" type="{http://lanit.ru/ws/pgu/reform_license}LicensiatType"/>
 *         &lt;choice>
 *           &lt;element name="RequestUL" type="{http://lanit.ru/ws/pgu/reform_license}RequestULType"/>
 *           &lt;element name="RequestIP" type="{http://lanit.ru/ws/pgu/reform_license}RequestIPType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReformLicenseRequestType", namespace = "http://lanit.ru/ws/pgu/reform_license", propOrder = {
    "clientType",
    "requestUL",
    "requestIP"
})
public class ReformLicenseRequestType {

    @XmlElement(name = "ClientType", namespace = "http://lanit.ru/ws/pgu/reform_license", required = true)
    protected String clientType;
    @XmlElement(name = "RequestUL", namespace = "http://lanit.ru/ws/pgu/reform_license")
    protected RequestULType requestUL;
    @XmlElement(name = "RequestIP", namespace = "http://lanit.ru/ws/pgu/reform_license")
    protected RequestIPType requestIP;

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientType(String value) {
        this.clientType = value;
    }

    /**
     * Gets the value of the requestUL property.
     * 
     * @return
     *     possible object is
     *     {@link RequestULType }
     *     
     */
    public RequestULType getRequestUL() {
        return requestUL;
    }

    /**
     * Sets the value of the requestUL property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestULType }
     *     
     */
    public void setRequestUL(RequestULType value) {
        this.requestUL = value;
    }

    /**
     * Gets the value of the requestIP property.
     * 
     * @return
     *     possible object is
     *     {@link RequestIPType }
     *     
     */
    public RequestIPType getRequestIP() {
        return requestIP;
    }

    /**
     * Sets the value of the requestIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestIPType }
     *     
     */
    public void setRequestIP(RequestIPType value) {
        this.requestIP = value;
    }

}
