//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.reform_license;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Информация о представителе заявителя
 * 
 * <p>Java class for RepresentativeInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RepresentativeInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RepresentativeLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RepresentativeFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RepresentativeSecondName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepresentativeInfoType", namespace = "http://lanit.ru/ws/pgu/reform_license", propOrder = {
    "representativeLastName",
    "representativeFirstName",
    "representativeSecondName"
})
public class RepresentativeInfoType {

    @XmlElement(name = "RepresentativeLastName", namespace = "http://lanit.ru/ws/pgu/reform_license", required = true)
    protected String representativeLastName;
    @XmlElement(name = "RepresentativeFirstName", namespace = "http://lanit.ru/ws/pgu/reform_license", required = true)
    protected String representativeFirstName;
    @XmlElementRef(name = "RepresentativeSecondName", namespace = "http://lanit.ru/ws/pgu/reform_license", type = JAXBElement.class)
    protected JAXBElement<String> representativeSecondName;

    /**
     * Gets the value of the representativeLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentativeLastName() {
        return representativeLastName;
    }

    /**
     * Sets the value of the representativeLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentativeLastName(String value) {
        this.representativeLastName = value;
    }

    /**
     * Gets the value of the representativeFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentativeFirstName() {
        return representativeFirstName;
    }

    /**
     * Sets the value of the representativeFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentativeFirstName(String value) {
        this.representativeFirstName = value;
    }

    /**
     * Gets the value of the representativeSecondName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRepresentativeSecondName() {
        return representativeSecondName;
    }

    /**
     * Sets the value of the representativeSecondName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRepresentativeSecondName(JAXBElement<String> value) {
        this.representativeSecondName = ((JAXBElement<String> ) value);
    }

}
