//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Информация для изменения статуса заявки в ЛК
 *             
 * 
 * <p>Java class for ServiceResponseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceResponseInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderId">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="orgId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statusCode">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="orgCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="techCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancelAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="authToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceResponseInfoType", namespace = "http://lanit.ru/ws/pgu/changeorderinfo", propOrder = {
    "orderId",
    "statusCode",
    "comment",
    "cancelAllowed",
    "authToken"
})
public class ServiceResponseInfoType {

    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", required = true)
    protected ServiceResponseInfoType.OrderId orderId;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", required = true)
    protected ServiceResponseInfoType.StatusCode statusCode;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo")
    protected String comment;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo")
    protected Boolean cancelAllowed;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", required = true)
    protected String authToken;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceResponseInfoType.OrderId }
     *     
     */
    public ServiceResponseInfoType.OrderId getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceResponseInfoType.OrderId }
     *     
     */
    public void setOrderId(ServiceResponseInfoType.OrderId value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceResponseInfoType.StatusCode }
     *     
     */
    public ServiceResponseInfoType.StatusCode getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceResponseInfoType.StatusCode }
     *     
     */
    public void setStatusCode(ServiceResponseInfoType.StatusCode value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the cancelAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCancelAllowed() {
        return cancelAllowed;
    }

    /**
     * Sets the value of the cancelAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCancelAllowed(Boolean value) {
        this.cancelAllowed = value;
    }

    /**
     * Gets the value of the authToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * Sets the value of the authToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthToken(String value) {
        this.authToken = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="orgId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orgId"
    })
    public static class OrderId {

        @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo")
        protected String orgId;

        /**
         * Gets the value of the orgId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrgId() {
            return orgId;
        }

        /**
         * Sets the value of the orgId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrgId(String value) {
            this.orgId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="orgCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="techCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orgCode",
        "techCode"
    })
    public static class StatusCode {

        @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo")
        protected String orgCode;
        @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo")
        protected String techCode;

        /**
         * Gets the value of the orgCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrgCode() {
            return orgCode;
        }

        /**
         * Sets the value of the orgCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrgCode(String value) {
            this.orgCode = value;
        }

        /**
         * Gets the value of the techCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTechCode() {
            return techCode;
        }

        /**
         * Sets the value of the techCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTechCode(String value) {
            this.techCode = value;
        }

    }

}
