//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CatalogRequestAppDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogRequestAppDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="catalogInfo" type="{http://lanit.ru/ws/pgu/types}CatalogRequestInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogRequestAppDataType", namespace = "http://lanit.ru/ws/pgu/types", propOrder = {
    "catalogInfo"
})
public class CatalogRequestAppDataType {

    @XmlElement(namespace = "http://lanit.ru/ws/pgu/types", required = true)
    protected CatalogRequestInfoType catalogInfo;

    /**
     * Gets the value of the catalogInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogRequestInfoType }
     *     
     */
    public CatalogRequestInfoType getCatalogInfo() {
        return catalogInfo;
    }

    /**
     * Sets the value of the catalogInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogRequestInfoType }
     *     
     */
    public void setCatalogInfo(CatalogRequestInfoType value) {
        this.catalogInfo = value;
    }

}
