//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the my package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Error_QNAME = new QName("http://lanit.ru/ws/pgu/types", "error");
    private final static QName _CatalogRequest_QNAME = new QName("http://lanit.ru/ws/pgu", "CatalogRequest");
    private final static QName _RegisterRequest_QNAME = new QName("http://lanit.ru/ws/pgu", "RegisterRequest");
    private final static QName _CancelRequest_QNAME = new QName("http://lanit.ru/ws/pgu", "CancelRequest");
    private final static QName _OrderRequest_QNAME = new QName("http://lanit.ru/ws/pgu/changeorderinfo", "orderRequest");
    private final static QName _ServiceInfo_QNAME = new QName("http://lanit.ru/ws/pgu/changeorderinfo", "serviceInfo");
    private final static QName _ChangeOrderInfo_QNAME = new QName("http://lanit.ru/ws/pgu/changeorderinfo", "changeOrderInfo");
    private final static QName _StatusResponse_QNAME = new QName("http://lanit.ru/ws/pgu", "StatusResponse");
    private final static QName _CancelResponse_QNAME = new QName("http://lanit.ru/ws/pgu", "CancelResponse");
    private final static QName _CatalogResponse_QNAME = new QName("http://lanit.ru/ws/pgu", "CatalogResponse");
    private final static QName _RegisterResponse_QNAME = new QName("http://lanit.ru/ws/pgu", "RegisterResponse");
    private final static QName _StatusRequest_QNAME = new QName("http://lanit.ru/ws/pgu", "StatusRequest");
    private final static QName _CatalogRequestTypeMessage_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "Message");
    private final static QName _CatalogRequestTypeMessageData_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "MessageData");
    private final static QName _ServiceMessageDataTypeAppDocument_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "AppDocument");
    private final static QName _ServiceMessageDataTypeAppData_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "AppData");
    private final static QName _AppDocumentTypeBinaryData_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "BinaryData");
    private final static QName _AppDocumentTypeRequestCode_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "RequestCode");
    private final static QName _SubMessageTypeRequestIdRef_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "RequestIdRef");
    private final static QName _SubMessageTypeOriginator_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "Originator");
    private final static QName _SubMessageTypeDate_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "Date");
    private final static QName _SubMessageTypeServiceCode_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "ServiceCode");
    private final static QName _SubMessageTypeOriginRequestIdRef_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "OriginRequestIdRef");
    private final static QName _SubMessageTypeCaseNumber_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "CaseNumber");
    private final static QName _ServiceCancelResponseInfoTypeComment_QNAME = new QName("http://lanit.ru/ws/pgu/types", "Comment");
    private final static QName _ServiceCancelResponseInfoTypeResponseCode_QNAME = new QName("http://lanit.ru/ws/pgu/types", "ResponseCode");
    private final static QName _MessageTypeSubMessages_QNAME = new QName("http://smev.gosuslugi.ru/rev120315", "SubMessages");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: my
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CancelRequestType }
     * 
     */
    public CancelRequestType createCancelRequestType() {
        return new CancelRequestType();
    }

    /**
     * Create an instance of {@link CatalogRequestType }
     * 
     */
    public CatalogRequestType createCatalogRequestType() {
        return new CatalogRequestType();
    }

    /**
     * Create an instance of {@link ServiceMessageDataType }
     * 
     */
    public ServiceMessageDataType createServiceMessageDataType() {
        return new ServiceMessageDataType();
    }

    /**
     * Create an instance of {@link AppDocumentType }
     * 
     */
    public AppDocumentType createAppDocumentType() {
        return new AppDocumentType();
    }

    /**
     * Create an instance of {@link OrgExternalType }
     * 
     */
    public OrgExternalType createOrgExternalType() {
        return new OrgExternalType();
    }

    /**
     * Create an instance of {@link RegisterRequestType }
     * 
     */
    public RegisterRequestType createRegisterRequestType() {
        return new RegisterRequestType();
    }

    /**
     * Create an instance of {@link ServiceResponseInfoType.OrderId }
     * 
     */
    public ServiceResponseInfoType.OrderId createServiceResponseInfoTypeOrderId() {
        return new ServiceResponseInfoType.OrderId();
    }

    /**
     * Create an instance of {@link ServiceResponseInfoType }
     * 
     */
    public ServiceResponseInfoType createServiceResponseInfoType() {
        return new ServiceResponseInfoType();
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link CatalogResponseAppDataType }
     * 
     */
    public CatalogResponseAppDataType createCatalogResponseAppDataType() {
        return new CatalogResponseAppDataType();
    }

    /**
     * Create an instance of {@link CancelResponseType }
     * 
     */
    public CancelResponseType createCancelResponseType() {
        return new CancelResponseType();
    }

    /**
     * Create an instance of {@link OrderRequestType }
     * 
     */
    public OrderRequestType createOrderRequestType() {
        return new OrderRequestType();
    }

    /**
     * Create an instance of {@link SubMessageType }
     * 
     */
    public SubMessageType createSubMessageType() {
        return new SubMessageType();
    }

    /**
     * Create an instance of {@link ServiceCancelResponseInfoType }
     * 
     */
    public ServiceCancelResponseInfoType createServiceCancelResponseInfoType() {
        return new ServiceCancelResponseInfoType();
    }

    /**
     * Create an instance of {@link StatusRequestInfoType }
     * 
     */
    public StatusRequestInfoType createStatusRequestInfoType() {
        return new StatusRequestInfoType();
    }

    /**
     * Create an instance of {@link SubMessagesType }
     * 
     */
    public SubMessagesType createSubMessagesType() {
        return new SubMessagesType();
    }

    /**
     * Create an instance of {@link StatusRequestMessageDataType }
     * 
     */
    public StatusRequestMessageDataType createStatusRequestMessageDataType() {
        return new StatusRequestMessageDataType();
    }

    /**
     * Create an instance of {@link ServiceCancelRequestMessageDataType }
     * 
     */
    public ServiceCancelRequestMessageDataType createServiceCancelRequestMessageDataType() {
        return new ServiceCancelRequestMessageDataType();
    }

    /**
     * Create an instance of {@link ServiceMessageDataResponseType }
     * 
     */
    public ServiceMessageDataResponseType createServiceMessageDataResponseType() {
        return new ServiceMessageDataResponseType();
    }

    /**
     * Create an instance of {@link ServiceResponseAppDataType }
     * 
     */
    public ServiceResponseAppDataType createServiceResponseAppDataType() {
        return new ServiceResponseAppDataType();
    }

    /**
     * Create an instance of {@link ServiceCancelRequestResponseAppDataType }
     * 
     */
    public ServiceCancelRequestResponseAppDataType createServiceCancelRequestResponseAppDataType() {
        return new ServiceCancelRequestResponseAppDataType();
    }

    /**
     * Create an instance of {@link StatusRequestType }
     * 
     */
    public StatusRequestType createStatusRequestType() {
        return new StatusRequestType();
    }

    /**
     * Create an instance of {@link CatalogResponseMessageDataType }
     * 
     */
    public CatalogResponseMessageDataType createCatalogResponseMessageDataType() {
        return new CatalogResponseMessageDataType();
    }

    /**
     * Create an instance of {@link StatusResponseType }
     * 
     */
    public StatusResponseType createStatusResponseType() {
        return new StatusResponseType();
    }

    /**
     * Create an instance of {@link CatalogRequestMessageDataType }
     * 
     */
    public CatalogRequestMessageDataType createCatalogRequestMessageDataType() {
        return new CatalogRequestMessageDataType();
    }

    /**
     * Create an instance of {@link DictionaryItem }
     * 
     */
    public DictionaryItem createDictionaryItem() {
        return new DictionaryItem();
    }

    /**
     * Create an instance of {@link CatalogResponseType }
     * 
     */
    public CatalogResponseType createCatalogResponseType() {
        return new CatalogResponseType();
    }

    /**
     * Create an instance of {@link ServiceCancelRequestInfoType }
     * 
     */
    public ServiceCancelRequestInfoType createServiceCancelRequestInfoType() {
        return new ServiceCancelRequestInfoType();
    }

    /**
     * Create an instance of {@link RegisterResponseType }
     * 
     */
    public RegisterResponseType createRegisterResponseType() {
        return new RegisterResponseType();
    }

    /**
     * Create an instance of {@link CatalogRequestAppDataType }
     * 
     */
    public CatalogRequestAppDataType createCatalogRequestAppDataType() {
        return new CatalogRequestAppDataType();
    }

    /**
     * Create an instance of {@link StatusResponseInfoType }
     * 
     */
    public StatusResponseInfoType createStatusResponseInfoType() {
        return new StatusResponseInfoType();
    }

    /**
     * Create an instance of {@link ServiceErrorInfoType }
     * 
     */
    public ServiceErrorInfoType createServiceErrorInfoType() {
        return new ServiceErrorInfoType();
    }

    /**
     * Create an instance of {@link ServiceCancelRequestMessageDataResponseType }
     * 
     */
    public ServiceCancelRequestMessageDataResponseType createServiceCancelRequestMessageDataResponseType() {
        return new ServiceCancelRequestMessageDataResponseType();
    }

    /**
     * Create an instance of {@link StatusRequestAppDataType }
     * 
     */
    public StatusRequestAppDataType createStatusRequestAppDataType() {
        return new StatusRequestAppDataType();
    }

    /**
     * Create an instance of {@link CatalogRequestInfoType }
     * 
     */
    public CatalogRequestInfoType createCatalogRequestInfoType() {
        return new CatalogRequestInfoType();
    }

    /**
     * Create an instance of {@link StatusResponseAppDataType }
     * 
     */
    public StatusResponseAppDataType createStatusResponseAppDataType() {
        return new StatusResponseAppDataType();
    }

    /**
     * Create an instance of {@link ServiceRequestAppDataType }
     * 
     */
    public ServiceRequestAppDataType createServiceRequestAppDataType() {
        return new ServiceRequestAppDataType();
    }

    /**
     * Create an instance of {@link ServiceCancelRequestAppDataType }
     * 
     */
    public ServiceCancelRequestAppDataType createServiceCancelRequestAppDataType() {
        return new ServiceCancelRequestAppDataType();
    }

    /**
     * Create an instance of {@link ServiceInfoType }
     * 
     */
    public ServiceInfoType createServiceInfoType() {
        return new ServiceInfoType();
    }

    /**
     * Create an instance of {@link ServiceResponseInfoType.StatusCode }
     * 
     */
    public ServiceResponseInfoType.StatusCode createServiceResponseInfoTypeStatusCode() {
        return new ServiceResponseInfoType.StatusCode();
    }

    /**
     * Create an instance of {@link StatusResponseMessageDataType }
     * 
     */
    public StatusResponseMessageDataType createStatusResponseMessageDataType() {
        return new StatusResponseMessageDataType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceErrorInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/types", name = "error")
    public JAXBElement<ServiceErrorInfoType> createError(ServiceErrorInfoType value) {
        return new JAXBElement<ServiceErrorInfoType>(_Error_QNAME, ServiceErrorInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatalogRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "CatalogRequest")
    public JAXBElement<CatalogRequestType> createCatalogRequest(CatalogRequestType value) {
        return new JAXBElement<CatalogRequestType>(_CatalogRequest_QNAME, CatalogRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "RegisterRequest")
    public JAXBElement<RegisterRequestType> createRegisterRequest(RegisterRequestType value) {
        return new JAXBElement<RegisterRequestType>(_RegisterRequest_QNAME, RegisterRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "CancelRequest")
    public JAXBElement<CancelRequestType> createCancelRequest(CancelRequestType value) {
        return new JAXBElement<CancelRequestType>(_CancelRequest_QNAME, CancelRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", name = "orderRequest")
    public JAXBElement<OrderRequestType> createOrderRequest(OrderRequestType value) {
        return new JAXBElement<OrderRequestType>(_OrderRequest_QNAME, OrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", name = "serviceInfo")
    public JAXBElement<ServiceInfoType> createServiceInfo(ServiceInfoType value) {
        return new JAXBElement<ServiceInfoType>(_ServiceInfo_QNAME, ServiceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceResponseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", name = "changeOrderInfo")
    public JAXBElement<ServiceResponseInfoType> createChangeOrderInfo(ServiceResponseInfoType value) {
        return new JAXBElement<ServiceResponseInfoType>(_ChangeOrderInfo_QNAME, ServiceResponseInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "StatusResponse")
    public JAXBElement<StatusResponseType> createStatusResponse(StatusResponseType value) {
        return new JAXBElement<StatusResponseType>(_StatusResponse_QNAME, StatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "CancelResponse")
    public JAXBElement<CancelResponseType> createCancelResponse(CancelResponseType value) {
        return new JAXBElement<CancelResponseType>(_CancelResponse_QNAME, CancelResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatalogResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "CatalogResponse")
    public JAXBElement<CatalogResponseType> createCatalogResponse(CatalogResponseType value) {
        return new JAXBElement<CatalogResponseType>(_CatalogResponse_QNAME, CatalogResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "RegisterResponse")
    public JAXBElement<RegisterResponseType> createRegisterResponse(RegisterResponseType value) {
        return new JAXBElement<RegisterResponseType>(_RegisterResponse_QNAME, RegisterResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu", name = "StatusRequest")
    public JAXBElement<StatusRequestType> createStatusRequest(StatusRequestType value) {
        return new JAXBElement<StatusRequestType>(_StatusRequest_QNAME, StatusRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = CatalogRequestType.class)
    public JAXBElement<MessageType> createCatalogRequestTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, CatalogRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatalogRequestMessageDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = CatalogRequestType.class)
    public JAXBElement<CatalogRequestMessageDataType> createCatalogRequestTypeMessageData(CatalogRequestMessageDataType value) {
        return new JAXBElement<CatalogRequestMessageDataType>(_CatalogRequestTypeMessageData_QNAME, CatalogRequestMessageDataType.class, CatalogRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = CancelRequestType.class)
    public JAXBElement<MessageType> createCancelRequestTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, CancelRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceCancelRequestMessageDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = CancelRequestType.class)
    public JAXBElement<ServiceCancelRequestMessageDataType> createCancelRequestTypeMessageData(ServiceCancelRequestMessageDataType value) {
        return new JAXBElement<ServiceCancelRequestMessageDataType>(_CatalogRequestTypeMessageData_QNAME, ServiceCancelRequestMessageDataType.class, CancelRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AppDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "AppDocument", scope = ServiceMessageDataType.class)
    public JAXBElement<AppDocumentType> createServiceMessageDataTypeAppDocument(AppDocumentType value) {
        return new JAXBElement<AppDocumentType>(_ServiceMessageDataTypeAppDocument_QNAME, AppDocumentType.class, ServiceMessageDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceRequestAppDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "AppData", scope = ServiceMessageDataType.class)
    public JAXBElement<ServiceRequestAppDataType> createServiceMessageDataTypeAppData(ServiceRequestAppDataType value) {
        return new JAXBElement<ServiceRequestAppDataType>(_ServiceMessageDataTypeAppData_QNAME, ServiceRequestAppDataType.class, ServiceMessageDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "BinaryData", scope = AppDocumentType.class)
    public JAXBElement<byte[]> createAppDocumentTypeBinaryData(byte[] value) {
        return new JAXBElement<byte[]>(_AppDocumentTypeBinaryData_QNAME, byte[].class, AppDocumentType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "RequestCode", scope = AppDocumentType.class)
    public JAXBElement<String> createAppDocumentTypeRequestCode(String value) {
        return new JAXBElement<String>(_AppDocumentTypeRequestCode_QNAME, String.class, AppDocumentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = StatusResponseType.class)
    public JAXBElement<MessageType> createStatusResponseTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, StatusResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusResponseMessageDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = StatusResponseType.class)
    public JAXBElement<StatusResponseMessageDataType> createStatusResponseTypeMessageData(StatusResponseMessageDataType value) {
        return new JAXBElement<StatusResponseMessageDataType>(_CatalogRequestTypeMessageData_QNAME, StatusResponseMessageDataType.class, StatusResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = CatalogResponseType.class)
    public JAXBElement<MessageType> createCatalogResponseTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, CatalogResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatalogResponseMessageDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = CatalogResponseType.class)
    public JAXBElement<CatalogResponseMessageDataType> createCatalogResponseTypeMessageData(CatalogResponseMessageDataType value) {
        return new JAXBElement<CatalogResponseMessageDataType>(_CatalogRequestTypeMessageData_QNAME, CatalogResponseMessageDataType.class, CatalogResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = RegisterRequestType.class)
    public JAXBElement<MessageType> createRegisterRequestTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, RegisterRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceMessageDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = RegisterRequestType.class)
    public JAXBElement<ServiceMessageDataType> createRegisterRequestTypeMessageData(ServiceMessageDataType value) {
        return new JAXBElement<ServiceMessageDataType>(_CatalogRequestTypeMessageData_QNAME, ServiceMessageDataType.class, RegisterRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = RegisterResponseType.class)
    public JAXBElement<MessageType> createRegisterResponseTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, RegisterResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceMessageDataResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = RegisterResponseType.class)
    public JAXBElement<ServiceMessageDataResponseType> createRegisterResponseTypeMessageData(ServiceMessageDataResponseType value) {
        return new JAXBElement<ServiceMessageDataResponseType>(_CatalogRequestTypeMessageData_QNAME, ServiceMessageDataResponseType.class, RegisterResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = CancelResponseType.class)
    public JAXBElement<MessageType> createCancelResponseTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, CancelResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceCancelRequestMessageDataResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = CancelResponseType.class)
    public JAXBElement<ServiceCancelRequestMessageDataResponseType> createCancelResponseTypeMessageData(ServiceCancelRequestMessageDataResponseType value) {
        return new JAXBElement<ServiceCancelRequestMessageDataResponseType>(_CatalogRequestTypeMessageData_QNAME, ServiceCancelRequestMessageDataResponseType.class, CancelResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "RequestIdRef", scope = SubMessageType.class)
    public JAXBElement<String> createSubMessageTypeRequestIdRef(String value) {
        return new JAXBElement<String>(_SubMessageTypeRequestIdRef_QNAME, String.class, SubMessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrgExternalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Originator", scope = SubMessageType.class)
    public JAXBElement<OrgExternalType> createSubMessageTypeOriginator(OrgExternalType value) {
        return new JAXBElement<OrgExternalType>(_SubMessageTypeOriginator_QNAME, OrgExternalType.class, SubMessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Date", scope = SubMessageType.class)
    public JAXBElement<XMLGregorianCalendar> createSubMessageTypeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SubMessageTypeDate_QNAME, XMLGregorianCalendar.class, SubMessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "ServiceCode", scope = SubMessageType.class)
    public JAXBElement<String> createSubMessageTypeServiceCode(String value) {
        return new JAXBElement<String>(_SubMessageTypeServiceCode_QNAME, String.class, SubMessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "OriginRequestIdRef", scope = SubMessageType.class)
    public JAXBElement<String> createSubMessageTypeOriginRequestIdRef(String value) {
        return new JAXBElement<String>(_SubMessageTypeOriginRequestIdRef_QNAME, String.class, SubMessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "CaseNumber", scope = SubMessageType.class)
    public JAXBElement<String> createSubMessageTypeCaseNumber(String value) {
        return new JAXBElement<String>(_SubMessageTypeCaseNumber_QNAME, String.class, SubMessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/types", name = "Comment", scope = ServiceCancelResponseInfoType.class)
    public JAXBElement<String> createServiceCancelResponseInfoTypeComment(String value) {
        return new JAXBElement<String>(_ServiceCancelResponseInfoTypeComment_QNAME, String.class, ServiceCancelResponseInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lanit.ru/ws/pgu/types", name = "ResponseCode", scope = ServiceCancelResponseInfoType.class)
    public JAXBElement<ResponseCodeType> createServiceCancelResponseInfoTypeResponseCode(ResponseCodeType value) {
        return new JAXBElement<ResponseCodeType>(_ServiceCancelResponseInfoTypeResponseCode_QNAME, ResponseCodeType.class, ServiceCancelResponseInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceCancelRequestAppDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "AppData", scope = ServiceCancelRequestMessageDataType.class)
    public JAXBElement<ServiceCancelRequestAppDataType> createServiceCancelRequestMessageDataTypeAppData(ServiceCancelRequestAppDataType value) {
        return new JAXBElement<ServiceCancelRequestAppDataType>(_ServiceMessageDataTypeAppData_QNAME, ServiceCancelRequestAppDataType.class, ServiceCancelRequestMessageDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubMessagesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "SubMessages", scope = MessageType.class)
    public JAXBElement<SubMessagesType> createMessageTypeSubMessages(SubMessagesType value) {
        return new JAXBElement<SubMessagesType>(_MessageTypeSubMessages_QNAME, SubMessagesType.class, MessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrgExternalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Originator", scope = MessageType.class)
    public JAXBElement<OrgExternalType> createMessageTypeOriginator(OrgExternalType value) {
        return new JAXBElement<OrgExternalType>(_SubMessageTypeOriginator_QNAME, OrgExternalType.class, MessageType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "Message", scope = StatusRequestType.class)
    public JAXBElement<MessageType> createStatusRequestTypeMessage(MessageType value) {
        return new JAXBElement<MessageType>(_CatalogRequestTypeMessage_QNAME, MessageType.class, StatusRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusRequestMessageDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://smev.gosuslugi.ru/rev120315", name = "MessageData", scope = StatusRequestType.class)
    public JAXBElement<StatusRequestMessageDataType> createStatusRequestTypeMessageData(StatusRequestMessageDataType value) {
        return new JAXBElement<StatusRequestMessageDataType>(_CatalogRequestTypeMessageData_QNAME, StatusRequestMessageDataType.class, StatusRequestType.class, value);
    }

}
