//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceOrgCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reestrId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="eServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceInfoType", namespace = "http://lanit.ru/ws/pgu/changeorderinfo", propOrder = {
    "serviceOrgCode",
    "reestrId",
    "eServiceId"
})
public class ServiceInfoType {

    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", required = true, nillable = true)
    protected String serviceOrgCode;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", required = true, nillable = true)
    protected String reestrId;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", required = true, nillable = true)
    protected String eServiceId;

    /**
     * Gets the value of the serviceOrgCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceOrgCode() {
        return serviceOrgCode;
    }

    /**
     * Sets the value of the serviceOrgCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceOrgCode(String value) {
        this.serviceOrgCode = value;
    }

    /**
     * Gets the value of the reestrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReestrId() {
        return reestrId;
    }

    /**
     * Sets the value of the reestrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReestrId(String value) {
        this.reestrId = value;
    }

    /**
     * Gets the value of the eServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEServiceId() {
        return eServiceId;
    }

    /**
     * Sets the value of the eServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEServiceId(String value) {
        this.eServiceId = value;
    }

}
