//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceCancelRequestResponseAppDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceCancelRequestResponseAppDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="CancelResponseInfo" type="{http://lanit.ru/ws/pgu/types}ServiceCancelResponseInfoType"/>
 *         &lt;element ref="{http://lanit.ru/ws/pgu/types}error"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceCancelRequestResponseAppDataType", namespace = "http://lanit.ru/ws/pgu/types", propOrder = {
    "cancelResponseInfo",
    "error"
})
public class ServiceCancelRequestResponseAppDataType {

    @XmlElement(name = "CancelResponseInfo", namespace = "http://lanit.ru/ws/pgu/types")
    protected ServiceCancelResponseInfoType cancelResponseInfo;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/types")
    protected ServiceErrorInfoType error;

    /**
     * Gets the value of the cancelResponseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCancelResponseInfoType }
     *     
     */
    public ServiceCancelResponseInfoType getCancelResponseInfo() {
        return cancelResponseInfo;
    }

    /**
     * Sets the value of the cancelResponseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCancelResponseInfoType }
     *     
     */
    public void setCancelResponseInfo(ServiceCancelResponseInfoType value) {
        this.cancelResponseInfo = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceErrorInfoType }
     *     
     */
    public ServiceErrorInfoType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceErrorInfoType }
     *     
     */
    public void setError(ServiceErrorInfoType value) {
        this.error = value;
    }

}
