//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceMessageDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceMessageDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppData" type="{http://lanit.ru/ws/pgu/types}ServiceRequestAppDataType" minOccurs="0"/>
 *         &lt;element name="AppDocument" type="{http://smev.gosuslugi.ru/rev120315}AppDocumentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceMessageDataType", namespace = "http://smev.gosuslugi.ru/rev120315", propOrder = {
    "appData",
    "appDocument"
})
public class ServiceMessageDataType {

    @XmlElementRef(name = "AppData", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<ServiceRequestAppDataType> appData;
    @XmlElementRef(name = "AppDocument", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<AppDocumentType> appDocument;

    /**
     * Gets the value of the appData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ServiceRequestAppDataType }{@code >}
     *     
     */
    public JAXBElement<ServiceRequestAppDataType> getAppData() {
        return appData;
    }

    /**
     * Sets the value of the appData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ServiceRequestAppDataType }{@code >}
     *     
     */
    public void setAppData(JAXBElement<ServiceRequestAppDataType> value) {
        this.appData = ((JAXBElement<ServiceRequestAppDataType> ) value);
    }

    /**
     * Gets the value of the appDocument property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AppDocumentType }{@code >}
     *     
     */
    public JAXBElement<AppDocumentType> getAppDocument() {
        return appDocument;
    }

    /**
     * Sets the value of the appDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AppDocumentType }{@code >}
     *     
     */
    public void setAppDocument(JAXBElement<AppDocumentType> value) {
        this.appDocument = ((JAXBElement<AppDocumentType> ) value);
    }

}
