//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusResponseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusResponseInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pguId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="statusText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documents" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusResponseInfoType", namespace = "http://lanit.ru/ws/pgu/types", propOrder = {
    "pguId",
    "statusCode",
    "statusText",
    "documents"
})
public class StatusResponseInfoType {

    @XmlElement(namespace = "http://lanit.ru/ws/pgu/types", required = true)
    protected String pguId;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/types")
    protected int statusCode;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/types", required = true)
    protected String statusText;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/types", required = true, nillable = true)
    protected byte[] documents;

    /**
     * Gets the value of the pguId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPguId() {
        return pguId;
    }

    /**
     * Sets the value of the pguId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPguId(String value) {
        this.pguId = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     */
    public int getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     */
    public void setStatusCode(int value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusText() {
        return statusText;
    }

    /**
     * Sets the value of the statusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusText(String value) {
        this.statusText = value;
    }

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDocuments(byte[] value) {
        this.documents = ((byte[]) value);
    }

}
