//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubMessagesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubMessagesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubMessage" type="{http://smev.gosuslugi.ru/rev120315}SubMessageType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubMessagesType", namespace = "http://smev.gosuslugi.ru/rev120315", propOrder = {
    "subMessage"
})
public class SubMessagesType {

    @XmlElement(name = "SubMessage", namespace = "http://smev.gosuslugi.ru/rev120315", required = true)
    protected SubMessageType subMessage;

    /**
     * Gets the value of the subMessage property.
     * 
     * @return
     *     possible object is
     *     {@link SubMessageType }
     *     
     */
    public SubMessageType getSubMessage() {
        return subMessage;
    }

    /**
     * Sets the value of the subMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubMessageType }
     *     
     */
    public void setSubMessage(SubMessageType value) {
        this.subMessage = value;
    }

}
