//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.lanit.ws.pgu.beans.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SubMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://smev.gosuslugi.ru/rev120315}StatusType"/>
 *         &lt;element name="Originator" type="{http://smev.gosuslugi.ru/rev120315}OrgExternalType" minOccurs="0"/>
 *         &lt;element name="CaseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubRequestNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestIdRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="OriginRequestIdRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubMessageType", namespace = "http://smev.gosuslugi.ru/rev120315", propOrder = {
    "status",
    "originator",
    "caseNumber",
    "subRequestNumber",
    "requestIdRef",
    "serviceCode",
    "date",
    "originRequestIdRef"
})
public class SubMessageType {

    @XmlElement(name = "Status", namespace = "http://smev.gosuslugi.ru/rev120315", required = true, nillable = true)
    protected StatusType status;
    @XmlElementRef(name = "Originator", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<OrgExternalType> originator;
    @XmlElementRef(name = "CaseNumber", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<String> caseNumber;
    @XmlElement(name = "SubRequestNumber", namespace = "http://smev.gosuslugi.ru/rev120315", required = true, nillable = true)
    protected String subRequestNumber;
    @XmlElementRef(name = "RequestIdRef", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<String> requestIdRef;
    @XmlElementRef(name = "ServiceCode", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<String> serviceCode;
    @XmlElementRef(name = "Date", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> date;
    @XmlElementRef(name = "OriginRequestIdRef", namespace = "http://smev.gosuslugi.ru/rev120315", type = JAXBElement.class)
    protected JAXBElement<String> originRequestIdRef;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the originator property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link OrgExternalType }{@code >}
     *     
     */
    public JAXBElement<OrgExternalType> getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link OrgExternalType }{@code >}
     *     
     */
    public void setOriginator(JAXBElement<OrgExternalType> value) {
        this.originator = ((JAXBElement<OrgExternalType> ) value);
    }

    /**
     * Gets the value of the caseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseNumber() {
        return caseNumber;
    }

    /**
     * Sets the value of the caseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseNumber(JAXBElement<String> value) {
        this.caseNumber = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the subRequestNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubRequestNumber() {
        return subRequestNumber;
    }

    /**
     * Sets the value of the subRequestNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubRequestNumber(String value) {
        this.subRequestNumber = value;
    }

    /**
     * Gets the value of the requestIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRequestIdRef() {
        return requestIdRef;
    }

    /**
     * Sets the value of the requestIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRequestIdRef(JAXBElement<String> value) {
        this.requestIdRef = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setServiceCode(JAXBElement<String> value) {
        this.serviceCode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDate(JAXBElement<XMLGregorianCalendar> value) {
        this.date = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the originRequestIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOriginRequestIdRef() {
        return originRequestIdRef;
    }

    /**
     * Sets the value of the originRequestIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOriginRequestIdRef(JAXBElement<String> value) {
        this.originRequestIdRef = ((JAXBElement<String> ) value);
    }

}
