//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.get_license;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные об автомобиле
 * 
 * <p>Java class for CarInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Brand" type="{http://lanit.ru/ws/pgu/get_license}DictType"/>
 *         &lt;element name="BrandText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Model" type="{http://lanit.ru/ws/pgu/get_license}DictType"/>
 *         &lt;element name="ModelText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Colour" type="{http://lanit.ru/ws/pgu/get_license}DictType"/>
 *         &lt;element name="GosNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReleaseYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EcoClass" type="{http://lanit.ru/ws/pgu/get_license}DictType" minOccurs="0"/>
 *         &lt;element name="Vin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CarDocInfo" type="{http://lanit.ru/ws/pgu/get_license}CarDocInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarInfoType", namespace = "http://lanit.ru/ws/pgu/get_license", propOrder = {
    "brand",
    "brandText",
    "model",
    "modelText",
    "colour",
    "gosNumber",
    "releaseYear",
    "ecoClass",
    "vin",
    "carDocInfo"
})
public class CarInfoType {

    @XmlElement(name = "Brand", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected DictType brand;
    @XmlElementRef(name = "BrandText", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> brandText;
    @XmlElement(name = "Model", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected DictType model;
    @XmlElementRef(name = "ModelText", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> modelText;
    @XmlElement(name = "Colour", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected DictType colour;
    @XmlElement(name = "GosNumber", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected String gosNumber;
    @XmlElement(name = "ReleaseYear", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected String releaseYear;
    @XmlElementRef(name = "EcoClass", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<DictType> ecoClass;
    @XmlElementRef(name = "Vin", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> vin;
    @XmlElement(name = "CarDocInfo", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected CarDocInfoType carDocInfo;

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setBrand(DictType value) {
        this.brand = value;
    }

    /**
     * Gets the value of the brandText property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBrandText() {
        return brandText;
    }

    /**
     * Sets the value of the brandText property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBrandText(JAXBElement<String> value) {
        this.brandText = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setModel(DictType value) {
        this.model = value;
    }

    /**
     * Gets the value of the modelText property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getModelText() {
        return modelText;
    }

    /**
     * Sets the value of the modelText property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setModelText(JAXBElement<String> value) {
        this.modelText = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the colour property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setColour(DictType value) {
        this.colour = value;
    }

    /**
     * Gets the value of the gosNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGosNumber() {
        return gosNumber;
    }

    /**
     * Sets the value of the gosNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGosNumber(String value) {
        this.gosNumber = value;
    }

    /**
     * Gets the value of the releaseYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseYear() {
        return releaseYear;
    }

    /**
     * Sets the value of the releaseYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseYear(String value) {
        this.releaseYear = value;
    }

    /**
     * Gets the value of the ecoClass property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DictType }{@code >}
     *     
     */
    public JAXBElement<DictType> getEcoClass() {
        return ecoClass;
    }

    /**
     * Sets the value of the ecoClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DictType }{@code >}
     *     
     */
    public void setEcoClass(JAXBElement<DictType> value) {
        this.ecoClass = ((JAXBElement<DictType> ) value);
    }

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getVin() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setVin(JAXBElement<String> value) {
        this.vin = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the carDocInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CarDocInfoType }
     *     
     */
    public CarDocInfoType getCarDocInfo() {
        return carDocInfo;
    }

    /**
     * Sets the value of the carDocInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarDocInfoType }
     *     
     */
    public void setCarDocInfo(CarDocInfoType value) {
        this.carDocInfo = value;
    }

}
