//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.get_license;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LicensiatULType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LicensiatULType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirmName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrgForm" type="{http://lanit.ru/ws/pgu/get_license}DictType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LicensiatULType", namespace = "http://lanit.ru/ws/pgu/get_license", propOrder = {
    "fullName",
    "shortName",
    "firmName",
    "orgForm"
})
public class LicensiatULType {

    @XmlElement(name = "FullName", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected String fullName;
    @XmlElementRef(name = "ShortName", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> shortName;
    @XmlElementRef(name = "FirmName", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> firmName;
    @XmlElement(name = "OrgForm", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected DictType orgForm;

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setShortName(JAXBElement<String> value) {
        this.shortName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the firmName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFirmName() {
        return firmName;
    }

    /**
     * Sets the value of the firmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFirmName(JAXBElement<String> value) {
        this.firmName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the orgForm property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getOrgForm() {
        return orgForm;
    }

    /**
     * Sets the value of the orgForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setOrgForm(DictType value) {
        this.orgForm = value;
    }

}
