//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.lanit.ws.pgu.get_license;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Регистрационные данные
 * 
 * <p>Java class for RegistrationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistrationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Inn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InnForm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InnSeries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InnNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InnWho" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InnDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegNoName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegNoForm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegNoSeries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegNoNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegNoDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="RegDepartAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RepresentativeInfo" type="{http://lanit.ru/ws/pgu/get_license}RepresentativeInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationInfoType", namespace = "http://lanit.ru/ws/pgu/get_license", propOrder = {
    "inn",
    "innName",
    "innForm",
    "innSeries",
    "innNumber",
    "innWho",
    "innDate",
    "phone",
    "fax",
    "email",
    "regNo",
    "regNoName",
    "regNoForm",
    "regNoSeries",
    "regNoNumber",
    "regNoDate",
    "regDepartAddress",
    "representativeInfo"
})
public class RegistrationInfoType {

    @XmlElement(name = "Inn", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected String inn;
    @XmlElementRef(name = "InnName", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> innName;
    @XmlElementRef(name = "InnForm", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> innForm;
    @XmlElementRef(name = "InnSeries", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> innSeries;
    @XmlElementRef(name = "InnNumber", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> innNumber;
    @XmlElementRef(name = "InnWho", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> innWho;
    @XmlElementRef(name = "InnDate", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> innDate;
    @XmlElementRef(name = "Phone", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> phone;
    @XmlElementRef(name = "Fax", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> fax;
    @XmlElementRef(name = "Email", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> email;
    @XmlElement(name = "RegNo", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    protected String regNo;
    @XmlElementRef(name = "RegNoName", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> regNoName;
    @XmlElementRef(name = "RegNoForm", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> regNoForm;
    @XmlElementRef(name = "RegNoSeries", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> regNoSeries;
    @XmlElementRef(name = "RegNoNumber", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> regNoNumber;
    @XmlElement(name = "RegNoDate", namespace = "http://lanit.ru/ws/pgu/get_license", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar regNoDate;
    @XmlElementRef(name = "RegDepartAddress", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<String> regDepartAddress;
    @XmlElementRef(name = "RepresentativeInfo", namespace = "http://lanit.ru/ws/pgu/get_license", type = JAXBElement.class)
    protected JAXBElement<RepresentativeInfoType> representativeInfo;

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInn(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the innName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInnName() {
        return innName;
    }

    /**
     * Sets the value of the innName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInnName(JAXBElement<String> value) {
        this.innName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the innForm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInnForm() {
        return innForm;
    }

    /**
     * Sets the value of the innForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInnForm(JAXBElement<String> value) {
        this.innForm = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the innSeries property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInnSeries() {
        return innSeries;
    }

    /**
     * Sets the value of the innSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInnSeries(JAXBElement<String> value) {
        this.innSeries = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the innNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInnNumber() {
        return innNumber;
    }

    /**
     * Sets the value of the innNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInnNumber(JAXBElement<String> value) {
        this.innNumber = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the innWho property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInnWho() {
        return innWho;
    }

    /**
     * Sets the value of the innWho property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInnWho(JAXBElement<String> value) {
        this.innWho = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the innDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getInnDate() {
        return innDate;
    }

    /**
     * Sets the value of the innDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setInnDate(JAXBElement<XMLGregorianCalendar> value) {
        this.innDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPhone(JAXBElement<String> value) {
        this.phone = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFax(JAXBElement<String> value) {
        this.fax = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEmail(JAXBElement<String> value) {
        this.email = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the regNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegNo() {
        return regNo;
    }

    /**
     * Sets the value of the regNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegNo(String value) {
        this.regNo = value;
    }

    /**
     * Gets the value of the regNoName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRegNoName() {
        return regNoName;
    }

    /**
     * Sets the value of the regNoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRegNoName(JAXBElement<String> value) {
        this.regNoName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the regNoForm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRegNoForm() {
        return regNoForm;
    }

    /**
     * Sets the value of the regNoForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRegNoForm(JAXBElement<String> value) {
        this.regNoForm = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the regNoSeries property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRegNoSeries() {
        return regNoSeries;
    }

    /**
     * Sets the value of the regNoSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRegNoSeries(JAXBElement<String> value) {
        this.regNoSeries = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the regNoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRegNoNumber() {
        return regNoNumber;
    }

    /**
     * Sets the value of the regNoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRegNoNumber(JAXBElement<String> value) {
        this.regNoNumber = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the regNoDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegNoDate() {
        return regNoDate;
    }

    /**
     * Sets the value of the regNoDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegNoDate(XMLGregorianCalendar value) {
        this.regNoDate = value;
    }

    /**
     * Gets the value of the regDepartAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRegDepartAddress() {
        return regDepartAddress;
    }

    /**
     * Sets the value of the regDepartAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRegDepartAddress(JAXBElement<String> value) {
        this.regDepartAddress = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the representativeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RepresentativeInfoType }{@code >}
     *     
     */
    public JAXBElement<RepresentativeInfoType> getRepresentativeInfo() {
        return representativeInfo;
    }

    /**
     * Sets the value of the representativeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RepresentativeInfoType }{@code >}
     *     
     */
    public void setRepresentativeInfo(JAXBElement<RepresentativeInfoType> value) {
        this.representativeInfo = ((JAXBElement<RepresentativeInfoType> ) value);
    }

}
