//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:39:31 AM MSK 
//


package ru.laint.ws.pgu.beans.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dictionary", namespace = "http://lanit.ru/ws/commons")
public class Dictionary {

    @XmlElement(namespace = "http://lanit.ru/ws/commons")
    protected List<DictionaryItem> item;

    public List<DictionaryItem> getItem() {
        if (item == null) {
            item = new ArrayList<DictionaryItem>();
        }
        return this.item;
    }

    public void setItem(List<DictionaryItem> item) {
        this.item = item;
    }
}
