//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.29 at 11:31:15 AM MSK 
//


package ru.lanit.ws.pgu.beans.application.gosuslugi.smev.request.rev111111;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for AppliedDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppliedDocumentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://smev.gosuslugi.ru/request/rev111111}CodeDocument" minOccurs="0"/>
 *         &lt;element ref="{http://smev.gosuslugi.ru/request/rev111111}Name"/>
 *         &lt;element ref="{http://smev.gosuslugi.ru/request/rev111111}Number" minOccurs="0"/>
 *         &lt;element ref="{http://smev.gosuslugi.ru/request/rev111111}URL"/>
 *         &lt;element ref="{http://smev.gosuslugi.ru/request/rev111111}Type"/>
 *         &lt;element ref="{http://smev.gosuslugi.ru/request/rev111111}DigestValue" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://smev.gosuslugi.ru/request/rev111111}ID"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppliedDocumentType", namespace = "http://smev.gosuslugi.ru/request/rev111111", propOrder = {
    "codeDocument",
    "name",
    "number",
    "url",
    "type",
    "digestValue"
})
public class AppliedDocumentType {

    @XmlElement(name = "CodeDocument", namespace = "http://smev.gosuslugi.ru/request/rev111111")
    protected String codeDocument;
    @XmlElement(name = "Name", namespace = "http://smev.gosuslugi.ru/request/rev111111", required = true)
    protected String name;
    @XmlElement(name = "Number", namespace = "http://smev.gosuslugi.ru/request/rev111111")
    protected String number;
    @XmlElement(name = "URL", namespace = "http://smev.gosuslugi.ru/request/rev111111", required = true)
    protected String url;
    @XmlElement(name = "Type", namespace = "http://smev.gosuslugi.ru/request/rev111111", required = true)
    protected String type;
    @XmlElement(name = "DigestValue", namespace = "http://smev.gosuslugi.ru/request/rev111111")
    protected byte[] digestValue;
    @XmlAttribute(name = "ID", namespace = "http://smev.gosuslugi.ru/request/rev111111")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the codeDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeDocument() {
        return codeDocument;
    }

    /**
     * Sets the value of the codeDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeDocument(String value) {
        this.codeDocument = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the digestValue property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDigestValue() {
        return digestValue;
    }

    /**
     * Sets the value of the digestValue property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDigestValue(byte[] value) {
        this.digestValue = ((byte[]) value);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
